changelog:
  categories:
    - title: All Changes 🚀
      labels:
        - 'release'
    - title: New Features 🎉
      labels:
        - 'enhancement'
    - title: Bug Fix 💊
      labels:
        - 'bug'
    - title: Refactoring 🧹
      labels:
        - 'refactor'
    - title: Other Changes 🛠
      labels:
        - '*'
