name: Create release tag and release note.

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: 'Select the version type to bump'
        options:
          - major
          - minor
          - patch
        required: true

jobs:
  create-release-tag:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TZ: 'Asia/Tokyo'

    steps:
      - uses: actions/checkout@v2

      # 前回のりリースタグを取得する
      - name: Get previous tag
        id: pre_tag
        run: |
          echo "::set-output name=pre_tag::$(curl -H 'Accept: application/vnd.github.v3+json' -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)"

      # タグを生成する
      - name: Generate release tag
        id: release_tag
        run: |
          set -e

          input_version="${{ github.event.inputs.version }}"
          echo "input version: $input_version"

          # 前回のタグを取得して表示
          pre_tag="${{ steps.pre_tag.outputs.pre_tag }}"
          echo "Previous tag: $pre_tag"
          
          # "v"を取り除いてバージョン番号を抽出
          pre_tag="${pre_tag//v/}"
          IFS='.' read -r -a version <<< "$pre_tag"
          
          # 抽出したバージョン番号を表示
          echo "Extracted version: ${version[@]}"

          # バージョンアップのタイプを決定
          case $input_version in
            'major')
              ((version[0]=version[0]+1))
              version[1]=0
              version[2]=0
              ;;
            'minor')
              ((version[1]=version[1]+1))
              version[2]=0
              ;;
            'patch')
              ((version[2]=version[2]+1))
              ;;
          esac
      
          # 新しいタグを生成
          new_tag="v${version[0]}.${version[1]}.${version[2]}"
      
          # 生成した新しいタグを表示する
          echo "New tag: $new_tag"
      
          # 出力に新しいタグをセット
          echo "::set-output name=release_tag::$new_tag"

      # 現在の日付を取得しyyyymmdd形式に変換する
      - name: Get current date
        id: current_date
        run: echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      # 同日のリリースカウントを取得
      - name: Get today's release count
        id: release_count
        run: |
          # GitHubリポジトリから全リリースのリストを取得（JSON形式で）
          ALL_RELEASES_JSON=$(gh api repos/$GITHUB_REPOSITORY/releases --jq '.[] | {name: .name}')
          echo "All releases (JSON): $ALL_RELEASES_JSON"
        
          # JSONからリリース名を抽出
          ALL_RELEASES=$(echo "$ALL_RELEASES_JSON" | jq -r '.name')
          echo "All releases: $ALL_RELEASES"
        
          # 特定の日付にマッチするリリースをフィルタリング
          RELEASES=$(echo "$ALL_RELEASES" | jq -r 'select(startswith("naikist-${{ env.CURRENT_DATE }}"))')
          echo "Filtered releases: $RELEASES"
        
          # リリース名のリストをソート
          SORTED_RELEASES=$(echo "$RELEASES" | sort)
          echo "Sorted releases: $SORTED_RELEASES"
        
          # 最新のリリースからカウントを取得
          COUNT=$(echo "$SORTED_RELEASES" | tail -n 1 | grep -o -E '\d+$')
          echo "Count: $COUNT"
        
          # カウントが空かどうかを確認し、リリースカウントを設定
          if [[ -z "$COUNT" ]]; then
            echo "RELEASE_COUNT=1" >> $GITHUB_ENV
            echo "Release count set to 1"
          else
            echo "RELEASE_COUNT=$(($COUNT + 1))" >> $GITHUB_ENV
            echo "Release count set to $(($COUNT + 1))"
          fi
      
      # Notionからリリースノート情報を取得する
      - name: Get data from Notion
        run: |
          CURRENT_MILESTONE="naikist-${{ env.CURRENT_DATE }}"
          RESPONSE=$(curl -X POST 'https://api.notion.com/v1/databases/b76806a2a57c47a3ad8062beaf7a5591/query' \
            -H 'Authorization: Bearer ${{ secrets.NOTION_TOKEN }}' \
            -H 'Content-Type: application/json' \
            -H 'Notion-Version: 2022-06-28' \
            --data '{
              "filter": {
                "property": "マイルストーン",
                "select": {
                  "equals": "'"$CURRENT_MILESTONE"'"
                }
              }
            }')
          echo "::set-output name=notion_response::$RESPONSE"
        id: notion_data

      # リリースノートの本文を生成する
      - name: Generate release notes
        id: release_notes
        run: |
          RELEASE_NOTES="修正内容\n"
          JSON_DATA='${{ steps.notion_data.outputs.notion_response }}'
          while IFS= read -r line; do
            RELEASE_NOTES+="$line\n"
          done < <(echo $JSON_DATA | jq -r '.results[] | "- " + .properties.Lenear.rich_text[0].plain_text + " " + .properties.Name.title[0].plain_text')
      
          # 環境ファイルを使用して環境変数を設定
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo -e "$RELEASE_NOTES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # タグを切り、リリースノートを作成する
      - name: Create GitHub Release
        run: |
          gh release create ${{ steps.release_tag.outputs.release_tag }} \
          --title "naikist-${{ env.CURRENT_DATE }}-${{ env.RELEASE_COUNT }}" \
            --notes "$RELEASE_NOTES"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}