name: Create release tag and release note.

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: 'Select the version type to bump'
        options:
          - major
          - minor
          - patch
        required: true

jobs:
  create-release-tag:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TZ: 'Asia/Tokyo'

    steps:
      - uses: actions/checkout@v3

      # 前回のリリースタグを取得する
      - name: Get previous tag
        run: |
          PRE_TAG=$(curl -H 'Accept: application/vnd.github.v3+json' \
            -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
            https://api.github.com/repos/${{ github.repository }}/releases/latest \
            | jq -r .tag_name)
          echo "PRE_TAG=$PRE_TAG" >> $GITHUB_ENV

      # タグを生成する
      - name: Generate release tag
        run: |
          set -e

          input_version="${{ github.event.inputs.version }}"
          echo "input version: $input_version"

          # 前回のタグを取得して表示
          pre_tag="${{ env.PRE_TAG }}"
          echo "Previous tag: $pre_tag"
          
          # "v"を取り除いてバージョン番号を抽出
          pre_tag="${pre_tag//v/}"
          IFS='.' read -r -a version <<< "$pre_tag"
          
          # 抽出したバージョン番号を表示
          echo "Extracted version: ${version[@]}"

          # バージョンアップのタイプを決定
          case $input_version in
            'major')
              ((version[0]=version[0]+1))
              version[1]=0
              version[2]=0
              ;;
            'minor')
              ((version[1]=version[1]+1))
              version[2]=0
              ;;
            'patch')
              ((version[2]=version[2]+1))
              ;;
          esac

          # 新しいタグを生成
          new_tag="v${version[0]}.${version[1]}.${version[2]}"
          
          # 生成した新しいタグを表示する
          echo "New tag: $new_tag"
          
          # 出力に新しいタグをセット
          echo "RELEASE_TAG=$new_tag" >> $GITHUB_ENV
            # 現在の日付を取得しyyyymmdd形式に変換する
            - name: Get current date
              run: echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

            # 同日のリリースカウントを取得
            - name: Get today's release count
              run: |
                # 最新のリリースノートのタイトルを取得
                LATEST_RELEASE_TITLE=$(gh api repos/$GITHUB_REPOSITORY/releases/latest --jq '.name')
                echo "Latest release title: $LATEST_RELEASE_TITLE"
              
                # タイトルを'-'で分割し、日付部分を取得
                IFS='-' read -ra ADDR <<< "$LATEST_RELEASE_TITLE"
                LATEST_RELEASE_DATE="${ADDR[1]}"
                echo "Latest release date: $LATEST_RELEASE_DATE"
              
                # 日付の比較とカウントの設定
                if [[ "$LATEST_RELEASE_DATE" == "${{ env.CURRENT_DATE }}" ]]; then
                  # タイトルの末尾からカウントを抽出してインクリメント
                  COUNT=$((${ADDR[2]} + 1))
                else
                  COUNT=1
                fi
                echo "Release count: $COUNT"
                echo "RELEASE_COUNT=$COUNT" >> $GITHUB_ENV

            # リリースノートの本文を生成する
            - name: Generate release note
              run: |
                RELEASE_NOTE=$(curl -X POST \
                  -H 'Accept: application/vnd.github.v3+json' \
                  -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
                  https://api.github.com/repos/${{ github.repository }}/releases/generate-notes \
                  -d '{"tag_name":"${{ env.RELEASE_TAG }}", "previous_tag_name":"${{ env.PRE_TAG }}"}' \
                  | jq -r .body)
                echo "RELEASE_NOTE<<EOF" >> $GITHUB_ENV
                echo "$RELEASE_NOTE" >> $GITHUB_ENV
                echo "EOF" >> $GITHUB_ENV

            # タグを切り、リリースノートを作成する
            - name: Create GitHub Release
              run: |
                gh release create ${{ env.RELEASE_TAG }} \
                  --title "naikist-${{ env.CURRENT_DATE }}-${{ env.RELEASE_COUNT }}" \
                  --notes "$RELEASE_NOTE"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}